datalad/datalad-xnat

datalad_xnat/__init__.py
datalad_xnat/init.py
datalad_xnat/parser.py
datalad_xnat/resources/procedures/cfg_xnat_dataset.py
datalad_xnat/update.py

@mih I've made `init` functional and have the beginnings for `update`. There are a few aspects/implementation details that I'm uncertain about, and will leave some notes here. 
* I chose not to hook `update` into `addurls`. I don't see how we can anticipate all the possible ways people will want to structure their dataset (subdatasets, directories, etc) with the varying number of subjects, acquisitions, and files that a given project will have. I thought it might make more sense to stay simple and just do a lookup of subject info and then build csv tables that can be fed directly to `addurls` in a separate command line call. If people need to modify the default structure, they can easily do so before running `addurls`.
* I don't think the name "update" is a good fit for the current …

draft of update command 

---

datalad_xnat/init.py
datalad_xnat/parser.py
datalad_xnat/platform.py
datalad_xnat/tests/test_register.py
datalad_xnat/update.py
setup.cfg

From datalad/datalad-xnat#30 we already know that pyxnat is not a full
solution. Moreover, it seems to force us to perform more queries than
strictly necessary -- slowing operations.
Here I reimplement all necessary queries in a minimalistic fashion.
This has many holes, including error handling. But it works so far,
and is indeed faster (by performing only 75% of the previous numer of
queries).
Fixes datalad/datalad-xnat#17
Fixes datalad/datalad-xnat#10
Fixes datalad/datalad-xnat#11
Fixes datalad/datalad-xnat#32

Drop pyxnat and minimize queries

---

datalad_xnat/platform.py

In https://github.com/datalad/datalad-xnat/issues/8#issuecomment-929870134
I reported that an authentication attempt resulted in a TypeError.
I believe this is due to a change that happened in #33, which
implemented session.auth, but tried to call the attribute as a method.
This commit introduces the correct format, I believe.

BF: Use session.auth as an attribute, do not try to call it as a method

---

datalad_xnat/init.py

This is based on a suggestion by @mih to improve the error handling when
wrong credentials are passed to fix #8. While this change does not do
any proper error handling so far, it returns an exception raised during
authentication as a proper error.
Here is how it looks like:
```
$ datalad xnat-init https://xnat.kube.fz-juelich.de                                                           1 !
xnat_init(error): . (dataset) [During authentication the XNAT server sent RuntimeError(('Failed to access the XNAT server. Full error:\n%s', HTTPError('401 Client Error:  for url: https://xnat.kube.fz-juelich.de/data/JSESSION')))]
```
I think it would still be good to parse the HTTP response and create some proper error handling

ENH: Return an error result for exceptions during authentication

---

datalad_xnat/init.py
datalad_xnat/platform.py
datalad_xnat/resources/procedures/cfg_xnat_dataset.py
datalad_xnat/update.py

XNAT uses 'ID', but connectomeDB uses 'id'.
This changes makes it possible to generate a file URL table
from the connectomeDB too, but when generating the scans response
for HCP_Retest the server gives a 500 response.
However, I can successfully parse the `MGH_DIFF` dataset with this code!
Ping datalad/datalad-xnat#30
demo:
```sh
% datalad xnat-init --credential connectomedb https://db.humanconnectome.org/ -p MGH_DIFF
% datalad xnat-update --credential connectomedb -s ConnectomeDB_S01343
% datalad status --annex
22 annex'd files (3.3 GB recorded total size)
nothing to save, working tree clean
```

Support connectomeDB

---

datalad_xnat/parser.py
datalad_xnat/platform.py

It requires a base url with a trailing slash to do the right thing.
Given all URL suffixes are hand-crafted, we can simply not use it.
Fixes datalad/datalad-xnat#47
```
In [3]: urljoin('https://www.nitrc.org/ir/', 'data/JSESSION')
Out[3]: 'https://www.nitrc.org/ir/data/JSESSION'
In [4]: urljoin('https://www.nitrc.org/ir/', '/data/JSESSION')
Out[4]: 'https://www.nitrc.org/data/JSESSION'
In [5]: urljoin('https://www.nitrc.org/ir', '/data/JSESSION')
Out[5]: 'https://www.nitrc.org/data/JSESSION'
In [6]: urljoin('https://www.nitrc.org/ir', 'data/JSESSION')
Out[6]: 'https://www.nitrc.org/data/JSESSION'
```

Discontinue use of urljoin

---

datalad_xnat/tests/test_xnatcentral.py
datalad_xnat/update.py

Make xnat-update read the credential label from config if not given

---

datalad_xnat/init.py
datalad_xnat/platform.py

Following up on PR #44, this catches `HTTPError` from authentication request explicitly and tries to give a more meaningful message, instead of something like the rather generic ones coming from the server like "Client Error for url xxx" when providing invalid credentials.
Examples for invalid credentials showing result dict and its rendering:
```
❱ datalad -f json_pp xnat-init https://xnat.kube.fz-juelich.de                                                                                       
{
"action": "xnat_init",
"exception": "RuntimeError(Failed to access the XNAT server. Reason: unauthorized)",
"exception_traceback": "[init.py:__call__:105,platform.py:__init__:104,platform.py:__init__:95,models.py:raise_for_status:953]",
"message": [
"%s",
"Failed to access the XNAT server. …
```

Improve error handling

---

setup.cfg

For e.g. CapturedException. Moreover it makes sense to also use
datalad's minimum Python version (3.6).
Fixes datalad/datalad-xnat#67

We actually depend on datalad 0.15.0

---

datalad_xnat/update.py

Closes #24
Pass the --fast option to addurls. The URLS will be added, but the content won't be downloaded.

NF: add --fast option to update

---

datalad_xnat/init.py
datalad_xnat/platform.py

BF: Catch HTTP errors before using responses
Without this patch, we end up passing the content of an error response
on to JSON decoding etc., which is leading to quite uninformative
failures.
- Closes #68
- Closes #83

More on error handling

---

docs/source/acknowledgements.rst
docs/source/api.rst
docs/source/cmd.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/intro.rst
docs/source/links.inc
docs/source/settingup.rst
docs/source/tutorial.rst
docs/source/tutorial/authentication.rst
docs/source/tutorial/tracking_a_project.rst

This paves the way towards user-oriented documentation by supplying a base structure to the documentation.
I have added base content, such as acknowledgements and a bit of structure over various sections types, from the datalad-osf docs. The PR can be merged as is, and sections marked with ``[COMPLETE ME]`` can be filled in by everyone who wishes to make a contribution to the docs.
Fixes #88

DOC: Provide an initial structure and some base content for user-oriented docs

---

datalad_xnat/parser.py
datalad_xnat/update.py

This avoids cleanup procedures. Fixes datalad/datalad-xnat#51

Use tempfiles for the addurls file tables

---

datalad_xnat/tests/test_xnatcentral.py
datalad_xnat/update.py

Leave the saving to `addurls` instead of doing it outside. `addurls`
knows precisely what needs saving, and the save the outside, possibly
expensive, `status` call that is implied by `save`.
Fixes datalad/datalad-xnat#108

Properly save subdatasets too

---

datalad_xnat/init.py
datalad_xnat/platform.py

My rational to add this is UX-based: When running "datalad xnat-init"
it can take a while for the command to finish the query. Without any
change to the log level, there is nothing that the user is seeing -
the command just sits there and does not return until the query is
finished. Notifying the user about the process of authentication is
a quick feedback that there indeed is something happening.
Here's a gif before and after the change:

ENH: Add a logging info on starting the authentication process

---

datalad_xnat/query_files.py

Now
```
% datalad xnat-query-files --credential anonymous https://www.nitrc.org/ir --experiment NITRC_IR_E07478
xnat_query(ok): NITRC_IR_E07478/T1/highres001.nii.gz (file) [NIfTI]
xnat_query(ok): NITRC_IR_E07478/T1/highres001_defacemask.nii.gz (file) [NIfTI]
xnat_query(ok): NITRC_IR_E07478/T1/qc.gif (file) [SNAPSHOTS]
xnat_query(ok): NITRC_IR_E07478/T1/highres001_dicominfo.txt (file) [Text]
...
```

Make default `query_files` result rendering more useful

---

datalad_xnat/parser.py
datalad_xnat/update.py

```
% datalad xnat-init --credential anonymous --project studyforrest_rev003 https://www.nitrc.org/ir
% datalad xnat-update -s NITRC_IR_S03684 --collection MAT
```
Will only download files in the "MAT" resource/collection.
Multiple collections can be given.

Add possibility to constrain an update by a collection set

---

datalad_xnat/tests/test_xnatcentral.py

Add a couple of assertions on the level of the `_XNAT` class against
XNAT central. This should allow to test some low-level behavior more
easily than going through the command-level functions.
Also introduces constants to be used w/ other tests against XNAT
central, which should make it easier to get to more flexible unittests
that may eventually be used against different target instances.

TST: Add test for _XNAT

---

datalad_xnat/query_files.py

Should hopefully fix @oportoles observed KeyError in #84.

BF: Prevent a key error in case a record does not contain 'digest' section

---

docs/source/glossary.rst
docs/source/tutorial.rst
docs/source/tutorial/understanding-init.rst

First piece of information on some internals on the init command. 
We can merge it as is for now to make faster progress, but later PRs can dissect any information in this file into other files if a different documentation structure makes more sense. Anything about this section could be taken apart or changed in any way necessary.

Doc initinternals

---

datalad_xnat/init.py
datalad_xnat/parser.py
datalad_xnat/platform.py
datalad_xnat/query_files.py
datalad_xnat/tests/test_update.py
datalad_xnat/tests/test_xnatcentral.py
datalad_xnat/update.py

Also sketches where and how interactive exploration would take place in
`init()`.
Also fixes datalad/datalad-xnat#63 by inspecting the config, instead of
a directory in a dataset.

Rough outline of API changes

---

datalad_xnat/tests/test_nitrcir.py
datalad_xnat/tests/test_xnatcentral.py

Closes #29
Ultimately the aim here is to get to generic tests, that would loop over different definitions for target definitions.

TST: Add basic tests against NITRC-IR
